version: '3.8'

services:
  vietthang-fashion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vietthang-fashion-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
